/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void ClientSend() {
        assertAll(
                ()-> assertTrue(TestHelper.openPortWithSpecificIPAndPort("localhost", 8833)),
                ()-> assertTrue(TestHelper.clientSendMessage("Client is here")),
                ()-> assertTrue(TestHelper.serverReplyOnMessage("Ok")),
                ()-> assertTrue(TestHelper.addNewClient("localhost", 8844))
        );
    }
}
